// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LiveMap.i
 * This header file contains the SWIG interface of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

%module(directors="1", threads="1") LiveMap

// SWIG helper modules
%include "stdint.i"
%include "std_array.i"
%include "std_map.i"
%include "std_string.i"
%include "std_vector.i"
%include "typemaps.i"

// Assignemt operators are ignored, as there is no such thing in Python.
// Trying to export them issues a warning
%ignore *::operator=;

// Macro declarations
// Any macro used on the Fast DDS header files will give an error if it is not redefined here
#define FASTDDS_EXPORTED_API
#define eProsima_user_DllExport

%include "VSLAMCore.i"

%{
#include "LiveMap.hpp"

#include <fastdds/dds/core/LoanableSequence.hpp>
%}

%include <fastcdr/config.h>
%import(module="fastdds") "fastcdr/xcdr/optional.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableTypedCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableSequence.hpp"

////////////////////////////////////////////////////////
// Binding for class EIVA::VSLAM::LiveMap
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore EIVA::VSLAM::LiveMap::LiveMap(EIVA::VSLAM::LiveMap&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore EIVA::VSLAM::LiveMap::landmarks(EIVA::VSLAM::LiveMapLandmarkSequence&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore EIVA::VSLAM::LiveMap::landmarks() const;
%template(Landmark_t_vector) std::vector<EIVA::VSLAMCore::Landmark_t>;


%ignore EIVA::VSLAM::LiveMap::H_frame_0(EIVA::VSLAM::LiveMapPose&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore EIVA::VSLAM::LiveMap::H_frame_0() const;
%extend std::vector<double>
{
    const double* get_buffer() const
    {
        return self->data();
    }
}

%template(double_vector) std::vector<double>;


%template(_LiveMapSeq) eprosima::fastdds::dds::LoanableTypedCollection<EIVA::VSLAM::LiveMap, std::false_type>;
%template(LiveMapSeq) eprosima::fastdds::dds::LoanableSequence<EIVA::VSLAM::LiveMap, std::false_type>;

%extend eprosima::fastdds::dds::LoanableSequence<EIVA::VSLAM::LiveMap, std::false_type>
{
    size_t Count() const
    {
        return self->length();
    }

    const EIVA::VSLAM::LiveMap& At(size_t i) const
    {
        return (*self)[i];
    }
}
%typemap(csinterfaces) EIVA::VSLAM::LiveMap %{ global::System.IDisposable, IRTPSData %}
%typemap(cscode) EIVA::VSLAM::LiveMap
%{
  public IntPtr GetHandle()
  {
      return swigCPtr.Handle;
  }
%}
// Include the class interfaces
%include "LiveMap.hpp"

// Include the corresponding TopicDataType
%include "LiveMapPubSubTypes.i"

