// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LiveMap.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__EIVA_VSLAM_LIVEMAP_HPP
#define FAST_DDS_GENERATED__EIVA_VSLAM_LIVEMAP_HPP

#include <cstdint>
#include <utility>
#include <vector>

#include "VSLAMCore.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LIVEMAP_SOURCE)
#define LIVEMAP_DllAPI __declspec( dllexport )
#else
#define LIVEMAP_DllAPI __declspec( dllimport )
#endif // LIVEMAP_SOURCE
#else
#define LIVEMAP_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LIVEMAP_DllAPI
#endif // _WIN32

namespace EIVA {

namespace VSLAM {

const int32_t EIVA_MAX_LIVEMAP_BUFFER_SIZE = 495616;
typedef std::vector<EIVA::VSLAMCore::Landmark_t> LiveMapLandmarkSequence;

typedef std::vector<double> LiveMapPose;

/*!
 * @brief This class represents the structure LiveMap defined by the user in the IDL file.
 * @ingroup LiveMap
 */
class LiveMap
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport LiveMap()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~LiveMap()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object LiveMap that will be copied.
     */
    eProsima_user_DllExport LiveMap(
            const LiveMap& x)
    {
                    m_landmarks = x.m_landmarks;

                    m_H_frame_0 = x.m_H_frame_0;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object LiveMap that will be copied.
     */
    eProsima_user_DllExport LiveMap(
            LiveMap&& x) noexcept
    {
        m_landmarks = std::move(x.m_landmarks);
        m_H_frame_0 = std::move(x.m_H_frame_0);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object LiveMap that will be copied.
     */
    eProsima_user_DllExport LiveMap& operator =(
            const LiveMap& x)
    {

                    m_landmarks = x.m_landmarks;

                    m_H_frame_0 = x.m_H_frame_0;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object LiveMap that will be copied.
     */
    eProsima_user_DllExport LiveMap& operator =(
            LiveMap&& x) noexcept
    {

        m_landmarks = std::move(x.m_landmarks);
        m_H_frame_0 = std::move(x.m_H_frame_0);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x LiveMap object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const LiveMap& x) const
    {
        return (m_landmarks == x.m_landmarks &&
           m_H_frame_0 == x.m_H_frame_0);
    }

    /*!
     * @brief Comparison operator.
     * @param x LiveMap object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const LiveMap& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member landmarks
     * @param _landmarks New value to be copied in member landmarks
     */
    eProsima_user_DllExport void landmarks(
            const LiveMapLandmarkSequence& _landmarks)
    {
        m_landmarks = _landmarks;
    }

    /*!
     * @brief This function moves the value in member landmarks
     * @param _landmarks New value to be moved in member landmarks
     */
    eProsima_user_DllExport void landmarks(
            LiveMapLandmarkSequence&& _landmarks)
    {
        m_landmarks = std::move(_landmarks);
    }

    /*!
     * @brief This function returns a constant reference to member landmarks
     * @return Constant reference to member landmarks
     */
    eProsima_user_DllExport const LiveMapLandmarkSequence& landmarks() const
    {
        return m_landmarks;
    }

    /*!
     * @brief This function returns a reference to member landmarks
     * @return Reference to member landmarks
     */
    eProsima_user_DllExport LiveMapLandmarkSequence& landmarks()
    {
        return m_landmarks;
    }


    /*!
     * @brief This function copies the value in member H_frame_0
     * @param _H_frame_0 New value to be copied in member H_frame_0
     */
    eProsima_user_DllExport void H_frame_0(
            const LiveMapPose& _H_frame_0)
    {
        m_H_frame_0 = _H_frame_0;
    }

    /*!
     * @brief This function moves the value in member H_frame_0
     * @param _H_frame_0 New value to be moved in member H_frame_0
     */
    eProsima_user_DllExport void H_frame_0(
            LiveMapPose&& _H_frame_0)
    {
        m_H_frame_0 = std::move(_H_frame_0);
    }

    /*!
     * @brief This function returns a constant reference to member H_frame_0
     * @return Constant reference to member H_frame_0
     */
    eProsima_user_DllExport const LiveMapPose& H_frame_0() const
    {
        return m_H_frame_0;
    }

    /*!
     * @brief This function returns a reference to member H_frame_0
     * @return Reference to member H_frame_0
     */
    eProsima_user_DllExport LiveMapPose& H_frame_0()
    {
        return m_H_frame_0;
    }



private:

    LiveMapLandmarkSequence m_landmarks;
    LiveMapPose m_H_frame_0;

};

} // namespace VSLAM

} // namespace EIVA

#endif // _FAST_DDS_GENERATED_EIVA_VSLAM_LIVEMAP_HPP_


