// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LiveMapTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "LiveMapTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "LiveMap.hpp"

#include "VSLAMCore.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace EIVA {
namespace VSLAM {
void register_LiveMapLandmarkSequence_type_identifier(
        TypeIdentifierPair& type_ids_LiveMapLandmarkSequence)
{
    ReturnCode_t return_code_LiveMapLandmarkSequence {eprosima::fastdds::dds::RETCODE_OK};
    return_code_LiveMapLandmarkSequence =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "EIVA::VSLAM::LiveMapLandmarkSequence", type_ids_LiveMapLandmarkSequence);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_LiveMapLandmarkSequence)
    {
        AliasTypeFlag alias_flags_LiveMapLandmarkSequence = 0;
        QualifiedTypeName type_name_LiveMapLandmarkSequence = "EIVA::VSLAM::LiveMapLandmarkSequence";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_LiveMapLandmarkSequence;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_LiveMapLandmarkSequence;
        CompleteTypeDetail detail_LiveMapLandmarkSequence = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_LiveMapLandmarkSequence, ann_custom_LiveMapLandmarkSequence, type_name_LiveMapLandmarkSequence.to_string());
        CompleteAliasHeader header_LiveMapLandmarkSequence = TypeObjectUtils::build_complete_alias_header(detail_LiveMapLandmarkSequence);
        AliasMemberFlag related_flags_LiveMapLandmarkSequence = 0;
        return_code_LiveMapLandmarkSequence =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "anonymous_sequence_EIVA_VSLAMCore_Landmark_t_495616", type_ids_LiveMapLandmarkSequence);

        if (eprosima::fastdds::dds::RETCODE_OK != return_code_LiveMapLandmarkSequence)
        {
            return_code_LiveMapLandmarkSequence =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "EIVA::VSLAMCore::Landmark_t", type_ids_LiveMapLandmarkSequence);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_LiveMapLandmarkSequence)
            {
                EIVA::VSLAMCore::register_Landmark_t_type_identifier(type_ids_LiveMapLandmarkSequence);
            }
            bool element_identifier_anonymous_sequence_EIVA_VSLAMCore_Landmark_t_495616_ec {false};
            TypeIdentifier* element_identifier_anonymous_sequence_EIVA_VSLAMCore_Landmark_t_495616 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_LiveMapLandmarkSequence, element_identifier_anonymous_sequence_EIVA_VSLAMCore_Landmark_t_495616_ec))};
            if (!element_identifier_anonymous_sequence_EIVA_VSLAMCore_Landmark_t_495616_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                return;
            }
            EquivalenceKind equiv_kind_anonymous_sequence_EIVA_VSLAMCore_Landmark_t_495616 = EK_COMPLETE;
            if (TK_NONE == type_ids_LiveMapLandmarkSequence.type_identifier2()._d())
            {
                equiv_kind_anonymous_sequence_EIVA_VSLAMCore_Landmark_t_495616 = EK_BOTH;
            }
            CollectionElementFlag element_flags_anonymous_sequence_EIVA_VSLAMCore_Landmark_t_495616 = 0;
            PlainCollectionHeader header_anonymous_sequence_EIVA_VSLAMCore_Landmark_t_495616 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_EIVA_VSLAMCore_Landmark_t_495616, element_flags_anonymous_sequence_EIVA_VSLAMCore_Landmark_t_495616);
            {
                LBound bound = 495616;
                PlainSequenceLElemDefn seq_ldefn = TypeObjectUtils::build_plain_sequence_l_elem_defn(header_anonymous_sequence_EIVA_VSLAMCore_Landmark_t_495616, bound,
                            eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_EIVA_VSLAMCore_Landmark_t_495616));
                if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                        TypeObjectUtils::build_and_register_l_sequence_type_identifier(seq_ldefn, "anonymous_sequence_EIVA_VSLAMCore_Landmark_t_495616", type_ids_LiveMapLandmarkSequence))
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "anonymous_sequence_EIVA_VSLAMCore_Landmark_t_495616 already registered in TypeObjectRegistry for a different type.");
                }
            }
        }
        bool common_LiveMapLandmarkSequence_ec {false};
        CommonAliasBody common_LiveMapLandmarkSequence {TypeObjectUtils::build_common_alias_body(related_flags_LiveMapLandmarkSequence,
                TypeObjectUtils::retrieve_complete_type_identifier(type_ids_LiveMapLandmarkSequence, common_LiveMapLandmarkSequence_ec))};
        if (!common_LiveMapLandmarkSequence_ec)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "EIVA::VSLAM::LiveMapLandmarkSequence related TypeIdentifier inconsistent.");
            return;
        }
        eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_LiveMapLandmarkSequence;
        ann_custom_LiveMapLandmarkSequence.reset();
        CompleteAliasBody body_LiveMapLandmarkSequence = TypeObjectUtils::build_complete_alias_body(common_LiveMapLandmarkSequence,
                member_ann_builtin_LiveMapLandmarkSequence, ann_custom_LiveMapLandmarkSequence);
        CompleteAliasType alias_type_LiveMapLandmarkSequence = TypeObjectUtils::build_complete_alias_type(alias_flags_LiveMapLandmarkSequence,
                header_LiveMapLandmarkSequence, body_LiveMapLandmarkSequence);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_alias_type_object(alias_type_LiveMapLandmarkSequence,
                    type_name_LiveMapLandmarkSequence.to_string(), type_ids_LiveMapLandmarkSequence))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "EIVA::VSLAM::LiveMapLandmarkSequence already registered in TypeObjectRegistry for a different type.");
        }
    }
}

void register_LiveMapPose_type_identifier(
        TypeIdentifierPair& type_ids_LiveMapPose)
{
    ReturnCode_t return_code_LiveMapPose {eprosima::fastdds::dds::RETCODE_OK};
    return_code_LiveMapPose =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "EIVA::VSLAM::LiveMapPose", type_ids_LiveMapPose);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_LiveMapPose)
    {
        AliasTypeFlag alias_flags_LiveMapPose = 0;
        QualifiedTypeName type_name_LiveMapPose = "EIVA::VSLAM::LiveMapPose";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_LiveMapPose;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_LiveMapPose;
        CompleteTypeDetail detail_LiveMapPose = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_LiveMapPose, ann_custom_LiveMapPose, type_name_LiveMapPose.to_string());
        CompleteAliasHeader header_LiveMapPose = TypeObjectUtils::build_complete_alias_header(detail_LiveMapPose);
        AliasMemberFlag related_flags_LiveMapPose = 0;
        return_code_LiveMapPose =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "anonymous_sequence_double_16", type_ids_LiveMapPose);

        if (eprosima::fastdds::dds::RETCODE_OK != return_code_LiveMapPose)
        {
            return_code_LiveMapPose =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_LiveMapPose);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_LiveMapPose)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "Sequence element TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            bool element_identifier_anonymous_sequence_double_16_ec {false};
            TypeIdentifier* element_identifier_anonymous_sequence_double_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_LiveMapPose, element_identifier_anonymous_sequence_double_16_ec))};
            if (!element_identifier_anonymous_sequence_double_16_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                return;
            }
            EquivalenceKind equiv_kind_anonymous_sequence_double_16 = EK_COMPLETE;
            if (TK_NONE == type_ids_LiveMapPose.type_identifier2()._d())
            {
                equiv_kind_anonymous_sequence_double_16 = EK_BOTH;
            }
            CollectionElementFlag element_flags_anonymous_sequence_double_16 = 0;
            PlainCollectionHeader header_anonymous_sequence_double_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_double_16, element_flags_anonymous_sequence_double_16);
            {
                SBound bound = static_cast<SBound>(16);
                PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_double_16, bound,
                            eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_double_16));
                if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                        TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_double_16", type_ids_LiveMapPose))
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "anonymous_sequence_double_16 already registered in TypeObjectRegistry for a different type.");
                }
            }
        }
        bool common_LiveMapPose_ec {false};
        CommonAliasBody common_LiveMapPose {TypeObjectUtils::build_common_alias_body(related_flags_LiveMapPose,
                TypeObjectUtils::retrieve_complete_type_identifier(type_ids_LiveMapPose, common_LiveMapPose_ec))};
        if (!common_LiveMapPose_ec)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "EIVA::VSLAM::LiveMapPose related TypeIdentifier inconsistent.");
            return;
        }
        eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_LiveMapPose;
        ann_custom_LiveMapPose.reset();
        CompleteAliasBody body_LiveMapPose = TypeObjectUtils::build_complete_alias_body(common_LiveMapPose,
                member_ann_builtin_LiveMapPose, ann_custom_LiveMapPose);
        CompleteAliasType alias_type_LiveMapPose = TypeObjectUtils::build_complete_alias_type(alias_flags_LiveMapPose,
                header_LiveMapPose, body_LiveMapPose);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_alias_type_object(alias_type_LiveMapPose,
                    type_name_LiveMapPose.to_string(), type_ids_LiveMapPose))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "EIVA::VSLAM::LiveMapPose already registered in TypeObjectRegistry for a different type.");
        }
    }
}

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_LiveMap_type_identifier(
        TypeIdentifierPair& type_ids_LiveMap)
{

    ReturnCode_t return_code_LiveMap {eprosima::fastdds::dds::RETCODE_OK};
    return_code_LiveMap =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "EIVA::VSLAM::LiveMap", type_ids_LiveMap);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_LiveMap)
    {
        StructTypeFlag struct_flags_LiveMap = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_LiveMap = "EIVA::VSLAM::LiveMap";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_LiveMap;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_LiveMap;
        AppliedAnnotationSeq tmp_ann_custom_LiveMap;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_LiveMap;
        if (!tmp_ann_custom_LiveMap.empty())
        {
            ann_custom_LiveMap = tmp_ann_custom_LiveMap;
        }

        CompleteTypeDetail detail_LiveMap = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_LiveMap, ann_custom_LiveMap, type_name_LiveMap.to_string());
        CompleteStructHeader header_LiveMap;
        header_LiveMap = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_LiveMap);
        CompleteStructMemberSeq member_seq_LiveMap;
        {
            TypeIdentifierPair type_ids_landmarks;
            ReturnCode_t return_code_landmarks {eprosima::fastdds::dds::RETCODE_OK};
            return_code_landmarks =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "EIVA::VSLAM::LiveMapLandmarkSequence", type_ids_landmarks);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_landmarks)
            {
                EIVA::VSLAM::register_LiveMapLandmarkSequence_type_identifier(type_ids_landmarks);
            }
            StructMemberFlag member_flags_landmarks = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_landmarks = 0x00000000;
            bool common_landmarks_ec {false};
            CommonStructMember common_landmarks {TypeObjectUtils::build_common_struct_member(member_id_landmarks, member_flags_landmarks, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_landmarks, common_landmarks_ec))};
            if (!common_landmarks_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure landmarks member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_landmarks = "landmarks";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_landmarks;
            ann_custom_LiveMap.reset();
            CompleteMemberDetail detail_landmarks = TypeObjectUtils::build_complete_member_detail(name_landmarks, member_ann_builtin_landmarks, ann_custom_LiveMap);
            CompleteStructMember member_landmarks = TypeObjectUtils::build_complete_struct_member(common_landmarks, detail_landmarks);
            TypeObjectUtils::add_complete_struct_member(member_seq_LiveMap, member_landmarks);
        }
        {
            TypeIdentifierPair type_ids_H_frame_0;
            ReturnCode_t return_code_H_frame_0 {eprosima::fastdds::dds::RETCODE_OK};
            return_code_H_frame_0 =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "EIVA::VSLAM::LiveMapPose", type_ids_H_frame_0);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_H_frame_0)
            {
                EIVA::VSLAM::register_LiveMapPose_type_identifier(type_ids_H_frame_0);
            }
            StructMemberFlag member_flags_H_frame_0 = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_H_frame_0 = 0x00000001;
            bool common_H_frame_0_ec {false};
            CommonStructMember common_H_frame_0 {TypeObjectUtils::build_common_struct_member(member_id_H_frame_0, member_flags_H_frame_0, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_H_frame_0, common_H_frame_0_ec))};
            if (!common_H_frame_0_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure H_frame_0 member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_H_frame_0 = "H_frame_0";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_H_frame_0;
            ann_custom_LiveMap.reset();
            CompleteMemberDetail detail_H_frame_0 = TypeObjectUtils::build_complete_member_detail(name_H_frame_0, member_ann_builtin_H_frame_0, ann_custom_LiveMap);
            CompleteStructMember member_H_frame_0 = TypeObjectUtils::build_complete_struct_member(common_H_frame_0, detail_H_frame_0);
            TypeObjectUtils::add_complete_struct_member(member_seq_LiveMap, member_H_frame_0);
        }
        CompleteStructType struct_type_LiveMap = TypeObjectUtils::build_complete_struct_type(struct_flags_LiveMap, header_LiveMap, member_seq_LiveMap);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_LiveMap, type_name_LiveMap.to_string(), type_ids_LiveMap))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "EIVA::VSLAM::LiveMap already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace VSLAM

} // namespace EIVA

