// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file VSLAMCore.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__EIVA_VSLAMCORE_VSLAMCORE_HPP
#define FAST_DDS_GENERATED__EIVA_VSLAMCORE_VSLAMCORE_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(VSLAMCORE_SOURCE)
#define VSLAMCORE_DllAPI __declspec( dllexport )
#else
#define VSLAMCORE_DllAPI __declspec( dllimport )
#endif // VSLAMCORE_SOURCE
#else
#define VSLAMCORE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define VSLAMCORE_DllAPI
#endif // _WIN32

namespace EIVA {

namespace VSLAMCore {

/*!
 * @brief This class represents the structure Landmark_t defined by the user in the IDL file.
 * @ingroup VSLAMCore
 */
class Landmark_t
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Landmark_t()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Landmark_t()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Landmark_t that will be copied.
     */
    eProsima_user_DllExport Landmark_t(
            const Landmark_t& x)
    {
                    m_x = x.m_x;

                    m_y = x.m_y;

                    m_z = x.m_z;

                    m_r = x.m_r;

                    m_g = x.m_g;

                    m_b = x.m_b;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Landmark_t that will be copied.
     */
    eProsima_user_DllExport Landmark_t(
            Landmark_t&& x) noexcept
    {
        m_x = x.m_x;
        m_y = x.m_y;
        m_z = x.m_z;
        m_r = x.m_r;
        m_g = x.m_g;
        m_b = x.m_b;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Landmark_t that will be copied.
     */
    eProsima_user_DllExport Landmark_t& operator =(
            const Landmark_t& x)
    {

                    m_x = x.m_x;

                    m_y = x.m_y;

                    m_z = x.m_z;

                    m_r = x.m_r;

                    m_g = x.m_g;

                    m_b = x.m_b;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Landmark_t that will be copied.
     */
    eProsima_user_DllExport Landmark_t& operator =(
            Landmark_t&& x) noexcept
    {

        m_x = x.m_x;
        m_y = x.m_y;
        m_z = x.m_z;
        m_r = x.m_r;
        m_g = x.m_g;
        m_b = x.m_b;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Landmark_t object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Landmark_t& x) const
    {
        return (m_x == x.m_x &&
           m_y == x.m_y &&
           m_z == x.m_z &&
           m_r == x.m_r &&
           m_g == x.m_g &&
           m_b == x.m_b);
    }

    /*!
     * @brief Comparison operator.
     * @param x Landmark_t object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Landmark_t& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member x
     * @param _x New value for member x
     */
    eProsima_user_DllExport void x(
            double _x)
    {
        m_x = _x;
    }

    /*!
     * @brief This function returns the value of member x
     * @return Value of member x
     */
    eProsima_user_DllExport double x() const
    {
        return m_x;
    }

    /*!
     * @brief This function returns a reference to member x
     * @return Reference to member x
     */
    eProsima_user_DllExport double& x()
    {
        return m_x;
    }


    /*!
     * @brief This function sets a value in member y
     * @param _y New value for member y
     */
    eProsima_user_DllExport void y(
            double _y)
    {
        m_y = _y;
    }

    /*!
     * @brief This function returns the value of member y
     * @return Value of member y
     */
    eProsima_user_DllExport double y() const
    {
        return m_y;
    }

    /*!
     * @brief This function returns a reference to member y
     * @return Reference to member y
     */
    eProsima_user_DllExport double& y()
    {
        return m_y;
    }


    /*!
     * @brief This function sets a value in member z
     * @param _z New value for member z
     */
    eProsima_user_DllExport void z(
            double _z)
    {
        m_z = _z;
    }

    /*!
     * @brief This function returns the value of member z
     * @return Value of member z
     */
    eProsima_user_DllExport double z() const
    {
        return m_z;
    }

    /*!
     * @brief This function returns a reference to member z
     * @return Reference to member z
     */
    eProsima_user_DllExport double& z()
    {
        return m_z;
    }


    /*!
     * @brief This function sets a value in member r
     * @param _r New value for member r
     */
    eProsima_user_DllExport void r(
            uint8_t _r)
    {
        m_r = _r;
    }

    /*!
     * @brief This function returns the value of member r
     * @return Value of member r
     */
    eProsima_user_DllExport uint8_t r() const
    {
        return m_r;
    }

    /*!
     * @brief This function returns a reference to member r
     * @return Reference to member r
     */
    eProsima_user_DllExport uint8_t& r()
    {
        return m_r;
    }


    /*!
     * @brief This function sets a value in member g
     * @param _g New value for member g
     */
    eProsima_user_DllExport void g(
            uint8_t _g)
    {
        m_g = _g;
    }

    /*!
     * @brief This function returns the value of member g
     * @return Value of member g
     */
    eProsima_user_DllExport uint8_t g() const
    {
        return m_g;
    }

    /*!
     * @brief This function returns a reference to member g
     * @return Reference to member g
     */
    eProsima_user_DllExport uint8_t& g()
    {
        return m_g;
    }


    /*!
     * @brief This function sets a value in member b
     * @param _b New value for member b
     */
    eProsima_user_DllExport void b(
            uint8_t _b)
    {
        m_b = _b;
    }

    /*!
     * @brief This function returns the value of member b
     * @return Value of member b
     */
    eProsima_user_DllExport uint8_t b() const
    {
        return m_b;
    }

    /*!
     * @brief This function returns a reference to member b
     * @return Reference to member b
     */
    eProsima_user_DllExport uint8_t& b()
    {
        return m_b;
    }



private:

    double m_x{0.0};
    double m_y{0.0};
    double m_z{0.0};
    uint8_t m_r{0};
    uint8_t m_g{0};
    uint8_t m_b{0};

};
/*!
 * @brief This class represents the enumeration State_e defined by the user in the IDL file.
 * @ingroup VSLAMCore
 */
enum class State_e : int32_t
{
    NOT_INITIALIZED,
    RECORD,
    START,
    STOP,
    PAUSE
};

} // namespace VSLAMCore

} // namespace EIVA

#endif // _FAST_DDS_GENERATED_EIVA_VSLAMCORE_VSLAMCORE_HPP_


