// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file VSLAMCoreTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "VSLAMCoreTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "VSLAMCore.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace EIVA {
namespace VSLAMCore {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Landmark_t_type_identifier(
        TypeIdentifierPair& type_ids_Landmark_t)
{

    ReturnCode_t return_code_Landmark_t {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Landmark_t =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "EIVA::VSLAMCore::Landmark_t", type_ids_Landmark_t);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Landmark_t)
    {
        StructTypeFlag struct_flags_Landmark_t = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_Landmark_t = "EIVA::VSLAMCore::Landmark_t";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Landmark_t;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Landmark_t;
        CompleteTypeDetail detail_Landmark_t = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Landmark_t, ann_custom_Landmark_t, type_name_Landmark_t.to_string());
        CompleteStructHeader header_Landmark_t;
        header_Landmark_t = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Landmark_t);
        CompleteStructMemberSeq member_seq_Landmark_t;
        {
            TypeIdentifierPair type_ids_x;
            ReturnCode_t return_code_x {eprosima::fastdds::dds::RETCODE_OK};
            return_code_x =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_x);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_x)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "x Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_x = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_x = 0x00000000;
            bool common_x_ec {false};
            CommonStructMember common_x {TypeObjectUtils::build_common_struct_member(member_id_x, member_flags_x, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_x, common_x_ec))};
            if (!common_x_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure x member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_x = "x";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_x;
            ann_custom_Landmark_t.reset();
            CompleteMemberDetail detail_x = TypeObjectUtils::build_complete_member_detail(name_x, member_ann_builtin_x, ann_custom_Landmark_t);
            CompleteStructMember member_x = TypeObjectUtils::build_complete_struct_member(common_x, detail_x);
            TypeObjectUtils::add_complete_struct_member(member_seq_Landmark_t, member_x);
        }
        {
            TypeIdentifierPair type_ids_y;
            ReturnCode_t return_code_y {eprosima::fastdds::dds::RETCODE_OK};
            return_code_y =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_y);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_y)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "y Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_y = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_y = 0x00000001;
            bool common_y_ec {false};
            CommonStructMember common_y {TypeObjectUtils::build_common_struct_member(member_id_y, member_flags_y, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_y, common_y_ec))};
            if (!common_y_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure y member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_y = "y";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_y;
            ann_custom_Landmark_t.reset();
            CompleteMemberDetail detail_y = TypeObjectUtils::build_complete_member_detail(name_y, member_ann_builtin_y, ann_custom_Landmark_t);
            CompleteStructMember member_y = TypeObjectUtils::build_complete_struct_member(common_y, detail_y);
            TypeObjectUtils::add_complete_struct_member(member_seq_Landmark_t, member_y);
        }
        {
            TypeIdentifierPair type_ids_z;
            ReturnCode_t return_code_z {eprosima::fastdds::dds::RETCODE_OK};
            return_code_z =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_z);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_z)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "z Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_z = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_z = 0x00000002;
            bool common_z_ec {false};
            CommonStructMember common_z {TypeObjectUtils::build_common_struct_member(member_id_z, member_flags_z, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_z, common_z_ec))};
            if (!common_z_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure z member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_z = "z";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_z;
            ann_custom_Landmark_t.reset();
            CompleteMemberDetail detail_z = TypeObjectUtils::build_complete_member_detail(name_z, member_ann_builtin_z, ann_custom_Landmark_t);
            CompleteStructMember member_z = TypeObjectUtils::build_complete_struct_member(common_z, detail_z);
            TypeObjectUtils::add_complete_struct_member(member_seq_Landmark_t, member_z);
        }
        {
            TypeIdentifierPair type_ids_r;
            ReturnCode_t return_code_r {eprosima::fastdds::dds::RETCODE_OK};
            return_code_r =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_r);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_r)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "r Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_r = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_r = 0x00000003;
            bool common_r_ec {false};
            CommonStructMember common_r {TypeObjectUtils::build_common_struct_member(member_id_r, member_flags_r, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_r, common_r_ec))};
            if (!common_r_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure r member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_r = "r";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_r;
            ann_custom_Landmark_t.reset();
            CompleteMemberDetail detail_r = TypeObjectUtils::build_complete_member_detail(name_r, member_ann_builtin_r, ann_custom_Landmark_t);
            CompleteStructMember member_r = TypeObjectUtils::build_complete_struct_member(common_r, detail_r);
            TypeObjectUtils::add_complete_struct_member(member_seq_Landmark_t, member_r);
        }
        {
            TypeIdentifierPair type_ids_g;
            ReturnCode_t return_code_g {eprosima::fastdds::dds::RETCODE_OK};
            return_code_g =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_g);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_g)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "g Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_g = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_g = 0x00000004;
            bool common_g_ec {false};
            CommonStructMember common_g {TypeObjectUtils::build_common_struct_member(member_id_g, member_flags_g, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_g, common_g_ec))};
            if (!common_g_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure g member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_g = "g";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_g;
            ann_custom_Landmark_t.reset();
            CompleteMemberDetail detail_g = TypeObjectUtils::build_complete_member_detail(name_g, member_ann_builtin_g, ann_custom_Landmark_t);
            CompleteStructMember member_g = TypeObjectUtils::build_complete_struct_member(common_g, detail_g);
            TypeObjectUtils::add_complete_struct_member(member_seq_Landmark_t, member_g);
        }
        {
            TypeIdentifierPair type_ids_b;
            ReturnCode_t return_code_b {eprosima::fastdds::dds::RETCODE_OK};
            return_code_b =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_b);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_b)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "b Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_b = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_b = 0x00000005;
            bool common_b_ec {false};
            CommonStructMember common_b {TypeObjectUtils::build_common_struct_member(member_id_b, member_flags_b, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_b, common_b_ec))};
            if (!common_b_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure b member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_b = "b";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_b;
            ann_custom_Landmark_t.reset();
            CompleteMemberDetail detail_b = TypeObjectUtils::build_complete_member_detail(name_b, member_ann_builtin_b, ann_custom_Landmark_t);
            CompleteStructMember member_b = TypeObjectUtils::build_complete_struct_member(common_b, detail_b);
            TypeObjectUtils::add_complete_struct_member(member_seq_Landmark_t, member_b);
        }
        CompleteStructType struct_type_Landmark_t = TypeObjectUtils::build_complete_struct_type(struct_flags_Landmark_t, header_Landmark_t, member_seq_Landmark_t);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Landmark_t, type_name_Landmark_t.to_string(), type_ids_Landmark_t))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "EIVA::VSLAMCore::Landmark_t already registered in TypeObjectRegistry for a different type.");
        }
    }
}
void register_State_e_type_identifier(
        TypeIdentifierPair& type_ids_State_e)
{
    ReturnCode_t return_code_State_e {eprosima::fastdds::dds::RETCODE_OK};
    return_code_State_e =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "EIVA::VSLAMCore::State_e", type_ids_State_e);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_State_e)
    {
        EnumTypeFlag enum_flags_State_e = 0;
        BitBound bit_bound_State_e = 32;
        CommonEnumeratedHeader common_State_e = TypeObjectUtils::build_common_enumerated_header(bit_bound_State_e);
        QualifiedTypeName type_name_State_e = "EIVA::VSLAMCore::State_e";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_State_e;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_State_e;
        CompleteTypeDetail detail_State_e = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_State_e, ann_custom_State_e, type_name_State_e.to_string());
        CompleteEnumeratedHeader header_State_e = TypeObjectUtils::build_complete_enumerated_header(common_State_e, detail_State_e);
        CompleteEnumeratedLiteralSeq literal_seq_State_e;
        {
            EnumeratedLiteralFlag flags_NOT_INITIALIZED = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_NOT_INITIALIZED = TypeObjectUtils::build_common_enumerated_literal(0, flags_NOT_INITIALIZED);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_NOT_INITIALIZED;
            ann_custom_State_e.reset();
            MemberName name_NOT_INITIALIZED = "NOT_INITIALIZED";
            CompleteMemberDetail detail_NOT_INITIALIZED = TypeObjectUtils::build_complete_member_detail(name_NOT_INITIALIZED, member_ann_builtin_NOT_INITIALIZED, ann_custom_State_e);
            CompleteEnumeratedLiteral literal_NOT_INITIALIZED = TypeObjectUtils::build_complete_enumerated_literal(common_NOT_INITIALIZED, detail_NOT_INITIALIZED);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_State_e, literal_NOT_INITIALIZED);
        }
        {
            EnumeratedLiteralFlag flags_RECORD = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_RECORD = TypeObjectUtils::build_common_enumerated_literal(1, flags_RECORD);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_RECORD;
            ann_custom_State_e.reset();
            MemberName name_RECORD = "RECORD";
            CompleteMemberDetail detail_RECORD = TypeObjectUtils::build_complete_member_detail(name_RECORD, member_ann_builtin_RECORD, ann_custom_State_e);
            CompleteEnumeratedLiteral literal_RECORD = TypeObjectUtils::build_complete_enumerated_literal(common_RECORD, detail_RECORD);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_State_e, literal_RECORD);
        }
        {
            EnumeratedLiteralFlag flags_START = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_START = TypeObjectUtils::build_common_enumerated_literal(2, flags_START);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_START;
            ann_custom_State_e.reset();
            MemberName name_START = "START";
            CompleteMemberDetail detail_START = TypeObjectUtils::build_complete_member_detail(name_START, member_ann_builtin_START, ann_custom_State_e);
            CompleteEnumeratedLiteral literal_START = TypeObjectUtils::build_complete_enumerated_literal(common_START, detail_START);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_State_e, literal_START);
        }
        {
            EnumeratedLiteralFlag flags_STOP = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_STOP = TypeObjectUtils::build_common_enumerated_literal(3, flags_STOP);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_STOP;
            ann_custom_State_e.reset();
            MemberName name_STOP = "STOP";
            CompleteMemberDetail detail_STOP = TypeObjectUtils::build_complete_member_detail(name_STOP, member_ann_builtin_STOP, ann_custom_State_e);
            CompleteEnumeratedLiteral literal_STOP = TypeObjectUtils::build_complete_enumerated_literal(common_STOP, detail_STOP);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_State_e, literal_STOP);
        }
        {
            EnumeratedLiteralFlag flags_PAUSE = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_PAUSE = TypeObjectUtils::build_common_enumerated_literal(4, flags_PAUSE);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_PAUSE;
            ann_custom_State_e.reset();
            MemberName name_PAUSE = "PAUSE";
            CompleteMemberDetail detail_PAUSE = TypeObjectUtils::build_complete_member_detail(name_PAUSE, member_ann_builtin_PAUSE, ann_custom_State_e);
            CompleteEnumeratedLiteral literal_PAUSE = TypeObjectUtils::build_complete_enumerated_literal(common_PAUSE, detail_PAUSE);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_State_e, literal_PAUSE);
        }
        CompleteEnumeratedType enumerated_type_State_e = TypeObjectUtils::build_complete_enumerated_type(enum_flags_State_e, header_State_e,
                literal_seq_State_e);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_enumerated_type_object(enumerated_type_State_e, type_name_State_e.to_string(), type_ids_State_e))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "EIVA::VSLAMCore::State_e already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace VSLAMCore

} // namespace EIVA

